[package]
name = "why_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "why-rs/src/lib/lib.rs"

[[bin]]
name = "why"
path = "why-rs/src/main.rs"

[dependencies]
